[package]
name = "arcon_tests"
version = "0.0.0"
authors = ["Max Meldrum <mmeldrum@kth.se>"]
edition = "2018"
publish = false

[dependencies]
arcon = { path = "../arcon" }
prost = "0.9"

[build-dependencies]
arcon_build = { path = "../arcon_build"}
