[package]
name = "arcon_messages"
version = "0.1.1"
authors = ["Max Meldrum <mmeldrum@kth.se>"]
edition = "2018"
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/cda-group/arcon"
homepage = "https://github.com/cda-group/arcon"
description = """
Arcon's network message schema
"""

[dependencies]
kompact = { git = "https://github.com/kompics/kompact.git", branch = "master" }
protobuf = "2.0"

[build-dependencies]
protoc-rust = "2.0"
