[package]
name = "arcon_extra"
version = "0.1.0"
authors = ["Max Meldrum <mmeldrum@kth.se>"]
edition = "2018"
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/cda-group/arcon"
homepage = "https://github.com/cda-group/arcon"
description = """
Extra features for Arcon
"""

[features]
default = []
kafka = ["rdkafka"]

[dependencies]
rdkafka = { version = "~0.19", optional = true }
