[package]
name = "arcon_spec"
version = "0.1.0"
authors = ["Max Meldrum <mmeldrum@kth.se>"]
edition = "2018"
publish = false

[dependencies]
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
failure = "0.1.5"

[dev-dependencies]
tempfile = "3"
