[book]
title = "The Arcon User Guide"
authors = ["Max Meldrum"]
description = "A User Guide for Arcon."

language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "ayu"
curly-quotes = true
git-repository-url = "https://github.com/cda-group/arcon"
